### ISSUE TITLE
support for uploading from an url

### ISSUE THREAD

**Issue by sevaorlov** [popuparchive/voicebase-client-ruby#1]
Hi, thanks for the gem!

There is no support for uploading from an url right now, but I managed to do it with the following code and I though it might be helpful for someone:

```ruby
voicebase = VoiceBase::Client.new(...)
response = voicebase.agent.post do |request|
  request.url voicebase.api_endpoint + '/media'
  request.headers['Content-Type'] = 'multipart/form-data'
  request.body = { media: url }
end
VoiceBase::Response.new response
```

@pkarman, do you think I can submit a request with it?

**Comment by pkarman** [comment]
thanks @sevaorlov 

Are you asking whether you could submit a pull request to the gem? Or if that code will work to submit a request to Voicebase?

if the latter, all I can suggest is try it and see.

If the former, go ahead and prep a PR, with test(s) please.

**Comment by sevaorlov** [comment]
@pkarman, I've already tried it and it works :) I was just asking about preparing PR. 
ok, I'll submit it when I have time

**Comment by sevaorlov** [comment]
@pkarman, I've added a PR for it
